baseURL = 'https://d-e-d-e.github.io/'
languageCode = 'en-us'
title = 'Pwn & Dev Blog'
theme = 'terminal'

[params]
  themeColor = 'green'
  showIcons = true
  readMore = "Read more"

[params.logo]
  logoText = "dede:~#"
  logoHomeLink = "/"
